### PR TITLE
Add a Glitch tracker of mine

### PR DESCRIPTION
**Pull request by hello-smile6**
Please don't tax it too much.

### CODE REVIEW

**Comment by ngosang** [comment]
They will cut the service in hours.

**Comment by hello-smile6** [comment]
> They will cut the service in hours.

What?

**Comment by zyyr365** [comment]
您好，您发给我的邮件已经收到，谢谢。

**Comment by hello-smile6** [comment]
> 您好，您发给我的邮件已经收到，谢谢。

Auto-reply?

**Pull request closed without merging**
